### ISSUE TITLE
static api.json

### ISSUE THREAD

**Issue by RyGuyOlson** [rikbrown/hastrumpfiredmuelleryet.com#1]
Please update the api.json to be dynamic.

**Comment by rikbrown** [comment]
This is not on the extensive roadmap for this website. If you'd like to receive a copy of our roadmap, please follow Donald Trump on Twitter for updates, or alternatively send a stamped addressed envelope [to your local representative](https://actionnetwork.org/letters/tell-congress-draw-up-articles-of-impeachment-against-trump).

We gladly accept pull requests!
